language: java
jdk: openjdk8
before_install:
  - wget https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-mdk.zip
  - unzip -n forge-1.12.2-14.23.5.2768-mdk.zip
  - rm forge-1.12.2-14.23.5.2768-mdk.zip
install: ./gradlew setupCiWorkspace
script: ./gradlew build